version: '3.1'

services:
  traefik:
    image: traefik:1.6.6-alpine
    command: --api --docker
    ports:
      - "80:80"
      - "8000:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    build:
      context: .
      args:
        - NODE_ENV=development
    command: nodemon
    expose:
      - "3000"
    volumes:
      - .:/opt/app:delegated
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json
      - notused:/opt/app/node_modules
    environment:
      - JWT_SECRET=secret
      - NODE_ENV=development
      - DB_HOST=database
      - DB_NAME=chatapp
      - DB_PORT=27017
    depends_on:
      - redis
    user: root
    labels:
      - "traefik.frontend.rule=PathPrefix:/"

  redis:
    image: redis:4.0.11-alpine
    expose:
      - "6379"

  database:
    image: mongo:4.1.2-xenial
    restart: always
    volumes:
      - database-data:/data/db
    expose:
      - "27017"
  
volumes:
  notused:
  database-data:
