version: '3.1'

services:
  api:
    image: aidengaripoli/chat-app-api:$VERSION
    depends_on:
      - database
      - redis
    environment:
      - JWT_SECRET=$JWT_SECRET
      - NODE_ENV=production
      - DB_HOST=database
      - DB_NAME=chat-app
      - DB_PORT=27017
    networks:
      - web
      - api
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role != manager
      labels:
        - "traefik.docker.network=web"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:carted.io"
        - "traefik.port=3000"
        - "traefik.protocol=http"

  redis:
    image: redis:4.0.11-alpine
    networks:
      - api
    ports:
      - "$REDIS_PUBLIC_PORT:6379"

  database:
    image: mongo:4.0.2-xenial
    networks:
      - api
    volumes:
      - database-data:/data/db
    ports:
      - "$MONGO_PUBLIC_PORT:27017"
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  database-data:

networks:
  web:
    external: true
  api:
    external: true
