version: '3.1'

services:
  traefik:
    image: traefik:1.6.6-alpine
    command: --api --docker
    ports:
      - "80:80"
      - "$TRAEFIK_PUBLIC_PORT:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    image: aidengaripoli/chatapp-api:$VERSION
    expose:
      - "3000"
    depends_on:
      - database
      - redis
    environment:
      - JWT_SECRET=$JWT_SECRET
      - NODE_ENV=production
      - DB_HOST=database
      - DB_NAME=chatapp
      - DB_PORT=27017
    labels:
      - "traefik.frontend.rule=PathPrefix:/"
    deploy:
      replicas: 2

  redis:
    image: redis:4.0.11-alpine
    ports:
      - "$REDIS_PUBLIC_PORT:6379"

  database:
    image: mongo:4.0.2-xenial
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
    #   - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - database-data:/data/db
    ports:
      - "$MONGO_PUBLIC_PORT:27017"
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  notused:
  database-data:
